import { money, fmtRange } from "./utils.js";

const cap = (s) => String(s ?? "").charAt(0).toUpperCase() + String(s ?? "").slice(1);
const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

/**
 * Build a clean, printable HTML document for a trip plan and open it in a
 * hidden iframe, then trigger the browser's print dialog. Users choose
 * "Save as PDF" as the destination. Fully offline, no dependencies.
 */
export function downloadTripPdf(trip) {
  const plan = trip?.plan;
  if (!plan) return;
  const html = buildDocument(trip, plan);

  const frame = document.createElement("iframe");
  frame.setAttribute("aria-hidden", "true");
  frame.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden";
  document.body.appendChild(frame);

  const doc = frame.contentWindow.document;
  doc.open();
  doc.write(html);
  doc.close();

  const cleanup = () => setTimeout(() => frame.remove(), 1000);
  const win = frame.contentWindow;
  win.addEventListener("afterprint", cleanup, { once: true });

  // Wait for images to settle so the map/photos render in the PDF.
  const imgs = [...doc.images];
  const pending = imgs.filter((im) => !im.complete);
  const go = () => { win.focus(); win.print(); cleanup(); };
  if (pending.length === 0) {
    setTimeout(go, 100);
  } else {
    let left = pending.length;
    const done = () => { if (--left <= 0) go(); };
    pending.forEach((im) => { im.addEventListener("load", done, { once: true }); im.addEventListener("error", done, { once: true }); });
    setTimeout(go, 2500); // safety timeout
  }
}

function buildDocument(trip, plan) {
  const cur = plan.budget?.currency || "$";
  const title = `Trip to ${trip.location?.name || trip.destination}`;
  const meta = `${fmtRange(trip.dates.from, trip.dates.to)} · ${trip.travelers.total} Travelers · Budget: ${cap(trip.budget.tier)}`;

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>${esc(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: "Plus Jakarta Sans", -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #1f2937; margin: 0; padding: 32px 36px; }
  h1 { font-size: 26px; margin: 0 0 4px; color: #111827; }
  h2 { font-size: 17px; margin: 26px 0 10px; color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 5px; }
  h3 { font-size: 14px; margin: 14px 0 6px; }
  .meta { color: #6b7280; font-size: 13px; margin-bottom: 4px; }
  .summary { background: #f0f6ff; border: 1px solid #dbeafe; border-radius: 10px; padding: 12px 14px; font-size: 13px; margin: 16px 0; }
  .day { margin-bottom: 14px; page-break-inside: avoid; }
  .day__label { color: #6b7280; font-size: 12px; margin-bottom: 6px; }
  .act { display: flex; gap: 12px; padding: 7px 0; border-top: 1px solid #f3f4f6; }
  .act__time { flex: 0 0 74px; font-weight: 700; color: #2563eb; font-size: 12px; }
  .act__title { font-weight: 600; font-size: 13px; }
  .act__desc { color: #4b5563; font-size: 12px; }
  ul { margin: 6px 0; padding-left: 20px; font-size: 13px; }
  li { margin: 3px 0; }
  .row { display: flex; justify-content: space-between; font-size: 13px; padding: 4px 0; border-bottom: 1px solid #f3f4f6; }
  .total { display: flex; justify-content: space-between; font-weight: 800; font-size: 15px; padding: 8px 0; border-bottom: 2px solid #e5e7eb; }
  .warn { font-size: 13px; padding: 4px 0; color: #92400e; }
  .grid2 { columns: 2; column-gap: 24px; }
  .foot { margin-top: 28px; padding-top: 10px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; text-align: center; }
  @page { margin: 16mm; }
</style></head>
<body>
  <h1>✈ ${esc(title)}</h1>
  <div class="meta">${esc(meta)}</div>
  ${trip.location?.country ? `<div class="meta">${esc(trip.location.country)}${trip.location.timezone ? " · " + esc(trip.location.timezone) : ""}</div>` : ""}
  ${plan.summary ? `<div class="summary"><b>✨ AI Trip Summary</b><br>${esc(plan.summary)}</div>` : ""}

  ${itinerarySection(plan)}
  ${placesSection(plan)}
  ${budgetSection(plan, cur)}
  ${packingSection(plan)}
  ${warningsSection(plan)}

  <div class="foot">Generated by Travel Planner · ${esc(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }))}</div>
</body></html>`;
}

function itinerarySection(plan) {
  if (!plan.dailyPlan?.length) return "";
  const days = plan.dailyPlan.map((d) => `
    <div class="day">
      <h3>Day ${esc(d.day)}</h3>
      <div class="day__label">${esc(d.label)}</div>
      ${(d.activities || []).map((a) => `
        <div class="act">
          <div class="act__time">${esc(a.time)}</div>
          <div><div class="act__title">${esc(a.title)}</div><div class="act__desc">${esc(a.description)}</div></div>
        </div>`).join("")}
    </div>`).join("");
  return `<h2>Itinerary</h2>${days}`;
}

function placesSection(plan) {
  if (!plan.bestPlaces?.length) return "";
  const items = plan.bestPlaces.map((p) =>
    `<li><b>${esc(p.name)}</b>${p.category ? ` <i>(${esc(cap(p.category))})</i>` : ""} — ${esc(p.description)}</li>`).join("");
  return `<h2>Top Places</h2><ul>${items}</ul>`;
}

function budgetSection(plan, cur) {
  const b = plan.budget;
  if (!b) return "";
  const rows = (b.breakdown || []).map((r) =>
    `<div class="row"><span>${esc(r.label)}</span><b>${esc(money(r.amount, cur))}</b></div>`).join("");
  return `<h2>Budget</h2>
    <div class="total"><span>Total estimated budget</span><span>${esc(money(b.total, cur))}</span></div>
    ${rows}`;
}

function packingSection(plan) {
  if (!plan.packingList?.length) return "";
  return `<h2>Packing List</h2><ul class="grid2">${plan.packingList.map((p) => `<li>${esc(p)}</li>`).join("")}</ul>`;
}

function warningsSection(plan) {
  if (!plan.warnings?.length) return "";
  return `<h2>Warnings</h2>${plan.warnings.map((w) => `<div class="warn">⚠️ ${esc(w)}</div>`).join("")}`;
}
